### PR TITLE
[UPGRADE]

### PR DESCRIPTION
**Pull request by jjfantini**
Moving files to be compatible with Pydantic v2.

I have gone through the [Migration Guide](https://docs.pydantic.dev/latest/migration/#moved-in-pydantic-v2) and changed everything that needs to be changed. Most was compliant.

Next steps:
- [ x ] fix custom `ValidationError` returning this error: {a}
- [ ] fix ModelMetaClass error: {b}

a
```powershell
env_patito\Lib\site-packages\_pytest\assertion\rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests\test_model.py:8: in <module>
    import patito as pt
src\patito\__init__.py:4: in <module>
    from patito import exceptions, sql
src\patito\exceptions.py:6: in <module>
    class ValidationError(pydantic.ValidationError):
E   TypeError: type 'pydantic_core._pydantic_core.ValidationError' is not an acceptable base type
==================================================== short test summary info ==================================================== 
ERROR tests/test_model.py - TypeError: type 'pydantic_core._pydantic_core.ValidationError' is not an acceptable base type
```
b
```
It seems like the 'ModelMetaclass' is being imported from 'pydantic.main' in your code, but the error message suggests that 'ModelMetaclass' cannot be found in 'pydantic.main'. 
```

### CODE REVIEW

**Comment by jjfantini** [comment]
@brendancooley what do you think of this?

**Comment by brendancooley** [comment]
@jjfantini looks like we may be able to drop the `ModelMetaclass` entirely if we're willing to drop support for python 3.7

```
    # -- Class properties set by model metaclass --
    # This weird combination of a MetaClass + type annotation
    # in order to make the following work simultaneously:
    #     1. Make these dynamically constructed properties of the class.
    #     2. Have the correct type information for type checkers.
    #     3. Allow sphinx-autodoc to construct correct documentation.
    #     4. Be compatible with python 3.7.
    # Once we drop support for python 3.7, we can replace all of this with just a simple
    # combination of @property and @classmethod.
```

https://github.com/brendancooley/patito/blob/e4397acb08cd2b955c199139b61cfe5c40424435/src/patito/pydantic.py#L523

**Comment by jjfantini** [comment]
Honestly, given that `Python 3.7` has been @ `end-of-life` since 2023-06-27...I think it may be worth setting up to support:
- 3.8
- 3.9
- 3.10
- 3.11
- 3.12

Especially if we are upgrading to `Pydantic v2`, users will be using 3.8+

I don't think it's a beneficial practice to add complexity to the code to support an old version. Simpler codebase if we drop support.
Thoughts?

**Comment by brendancooley** [comment]
See #6 for a complete migration onto pydantic v2, will keep this open to discuss how to deal with classproperties on the `BaseModel`/`ModelMetaclass`

**Pull request closed without merging**
